baseURL = "https://mengdemao.github.io"
languageCode = "zh-cn"
paginate = 10
theme = "hyde"
title = "开发日志"

[params]
author = "mengdemao"
description = "个人笔记"

[[params.social]]
name = "github"
url = "https://github.com/mengdemao"
